const categoriesData = [
  {
    name: 'Pizzas',
    description: 'Stone-baked artisan pizzas with handcrafted dough and premium toppings',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    name: 'Burgers & Wraps',
    description: 'Juicy gourmet burgers with brioche buns, fresh crunch, and signature sauces',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    name: 'Asian & Bowls',
    description: 'Fragrant noodles, aromatic curries, and nourishing wholesome rice bowls',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    name: 'Pastas & Italian',
    description: 'Authentic handmade pastas simmered in slow-cooked sauces and herbs',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    name: 'Desserts & Bakery',
    description: 'Decadent chocolate cakes, warm churros, and velvety pastries',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
  {
    name: 'Beverages',
    description: 'Cold-pressed fresh juices, signature mocktails, and artisanal shakes',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    isActive: true,
  },
];

const foodItemsData = [
  {
    name: 'Truffle Mushroom Artisan Pizza',
    description: 'Wood-fired sourdough crust topped with wild portobello mushrooms, black truffle oil, fresh buffalo mozzarella, and thyme.',
    price: 349,
    category: 'Pizzas',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    isPopular: true,
    rating: 4.9,
    preparationTime: '20-25 mins',
    dietary: 'veg',
    calories: '540 kcal',
    ingredients: ['Sourdough', 'Buffalo Mozzarella', 'Wild Mushrooms', 'Truffle Oil', 'Thyme'],
  },
  {
    name: 'Spicy Pepperoni & Jalapeño Feast',
    description: 'Crispy pepperoni cups, fiery jalapeños, smoked chili honey drizzle, and aged cheddar over robust tomato concassé.',
    price: 389,
    category: 'Pizzas',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    isPopular: true,
    rating: 4.8,
    preparationTime: '20-25 mins',
    dietary: 'non-veg',
    calories: '680 kcal',
    ingredients: ['Spicy Pepperoni', 'Jalapeños', 'Smoked Cheddar', 'Chili Honey', 'Basil'],
  },
  {
    name: 'Classic Margherita Supreme',
    description: 'Sweet San Marzano tomato puree, Fior di Latte mozzarella, fragrant sweet basil leaves, and extra virgin olive oil.',
    price: 279,
    category: 'Pizzas',
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    isPopular: false,
    rating: 4.7,
    preparationTime: '15-20 mins',
    dietary: 'veg',
    calories: '490 kcal',
    ingredients: ['San Marzano Tomatoes', 'Fresh Mozzarella', 'EVOO', 'Organic Basil'],
  },
  {
    name: 'Double Smash Cheddar Burger',
    description: 'Two sizzling crispy-edge beef/plant patties, melted American cheddar, grilled onions, house secret sauce on toasted brioche.',
    price: 299,
    category: 'Burgers & Wraps',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    isPopular: true,
    rating: 4.9,
    preparationTime: '15-20 mins',
    dietary: 'non-veg',
    calories: '720 kcal',
    ingredients: ['Dual Patties', 'Melted Cheddar', 'Caramelized Onion', 'Secret Sauce', 'Brioche'],
  },
  {
    name: 'Crispy Chipotle Paneer Burger',
    description: 'Spiced golden paneer patty seasoned with smoked paprika, tossed in creamy chipotle slaw and pickled red gherkins.',
    price: 249,
    category: 'Burgers & Wraps',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    isPopular: true,
    rating: 4.7,
    preparationTime: '15-18 mins',
    dietary: 'veg',
    calories: '580 kcal',
    ingredients: ['Cottage Cheese Paneer', 'Chipotle Mayo', 'Crisp Slaw', 'Sesame Bun'],
  },
  {
    name: 'Avocado Green Goddess Wrap',
    description: 'Hass avocado chunks, baby spinach, roasted chickpeas, cucumber ribbons, and tangy herbaceous green goddess dressing.',
    price: 229,
    category: 'Burgers & Wraps',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    isPopular: false,
    rating: 4.6,
    preparationTime: '12-15 mins',
    dietary: 'vegan',
    calories: '390 kcal',
    ingredients: ['Hass Avocado', 'Spinach', 'Hummus', 'Roasted Chickpeas', 'Wholewheat Tortilla'],
  },
  {
    name: 'Spicy Tokyo Miso Ramen Bowl',
    description: 'Rich 12-hour savory broth, chewy handmade noodles, ajitsuke tamago egg, charred corn, scallions, nori seaweed, and chili oil.',
    price: 369,
    category: 'Asian & Bowls',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    isPopular: true,
    rating: 4.9,
    preparationTime: '20-25 mins',
    dietary: 'non-veg',
    calories: '560 kcal',
    ingredients: ['Ramen Broth', 'Wheat Noodles', 'Marinated Egg', 'Nori', 'Rayu Chili Oil'],
  },
  {
    name: 'Teriyaki Tofu Poke Bowl',
    description: 'Glazed crispy tofu over fragrant jasmine rice, edamame, shredded purple cabbage, pickled ginger, sesame, and sriracha mayo.',
    price: 319,
    category: 'Asian & Bowls',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    isPopular: true,
    rating: 4.8,
    preparationTime: '15-20 mins',
    dietary: 'vegan',
    calories: '450 kcal',
    ingredients: ['Crispy Tofu', 'Edamame', 'Jasmine Rice', 'Avocado', 'Teriyaki Glaze'],
  },
  {
    name: 'Creamy Tuscan Penne Alfredo',
    description: 'Al dente penne folded into velvety garlic parmesan cream sauce, sundried tomatoes, wilted spinach, and fresh cracked pepper.',
    price: 329,
    category: 'Pastas & Italian',
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281729?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    isPopular: true,
    rating: 4.8,
    preparationTime: '18-22 mins',
    dietary: 'veg',
    calories: '610 kcal',
    ingredients: ['Penne Pasta', 'Parmigiano Reggiano', 'Heavy Cream', 'Garlic', 'Sundried Tomatoes'],
  },
  {
    name: 'Slow-Cooked Bolognese Tagliatelle',
    description: 'Ribbon tagliatelle pasta bathed in slow-simmered rich savory meat ragù with rosemary, red wine reduction, and pecorino.',
    price: 379,
    category: 'Pastas & Italian',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    isPopular: false,
    rating: 4.7,
    preparationTime: '20-25 mins',
    dietary: 'non-veg',
    calories: '670 kcal',
    ingredients: ['Tagliatelle', 'Simmered Ragù', 'Red Wine Reduction', 'Pecorino Romano'],
  },
  {
    name: 'Molten Belgian Chocolate Lava Cake',
    description: 'Warm dark chocolate sponge with a flowing molten Valrhona chocolate core, served with vanilla bean gelato scoop.',
    price: 199,
    category: 'Desserts & Bakery',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    isPopular: true,
    rating: 4.9,
    preparationTime: '12-15 mins',
    dietary: 'veg',
    calories: '420 kcal',
    ingredients: ['70% Dark Chocolate', 'Madagascar Vanilla Bean', 'Butter', 'Cocoa Powder'],
  },
  {
    name: 'Classic New York Berry Cheesecake',
    description: 'Dense, velvety baked cream cheese filling over buttery graham cracker crust, topped with wild blueberry compote.',
    price: 219,
    category: 'Desserts & Bakery',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    isPopular: true,
    rating: 4.8,
    preparationTime: '10-12 mins',
    dietary: 'veg',
    calories: '460 kcal',
    ingredients: ['Philadelphia Cream Cheese', 'Graham Cracker', 'Blueberries', 'Lemon Zest'],
  },
  {
    name: 'Passionfruit Mango Cooler',
    description: 'Sun-ripened Alphonso mango purée infused with tangy passionfruit, sparkling soda, fresh mint leaves, and lime wedge.',
    price: 149,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    isPopular: true,
    rating: 4.7,
    preparationTime: '5-8 mins',
    dietary: 'vegan',
    calories: '120 kcal',
    ingredients: ['Alphonso Mango', 'Passion Fruit', 'Fresh Mint', 'Sparkling Soda'],
  },
  {
    name: 'Caramel Hazelnut Iced Frappé',
    description: 'Fresh espresso shot blended with creamy milk, crushed ice, roasted hazelnut syrup, whipped cream swirl, and caramel drizzle.',
    price: 179,
    category: 'Beverages',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    isPopular: true,
    rating: 4.8,
    preparationTime: '5-8 mins',
    dietary: 'veg',
    calories: '280 kcal',
    ingredients: ['Espresso', 'Hazelnut Syrup', 'Cream', 'Caramel Drizzle'],
  },
];

module.exports = { categoriesData, foodItemsData };
